apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pythonhelloworld-controller
  labels:
    app: pythonhelloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pythonhelloworld
  template:
    metadata:
      labels:
        app: pythonhelloworld
    spec:
      containers:
      - name: k8s-demo
        image: akolli/my-pyhton-image
        ports:
        - name: python-port
          containerPort: 4000