apiVersion: v1
kind: Service
metadata:
  name: pythonhelloworld-service
spec:
  ports:
  - port: 41001
    targetPort: python-port
    protocol: TCP
  selector:
    app: pythonhelloworld
  type: NodePort