apiVersion: v1
kind: Pod
metadata:
  name: redispod1
  labels:
    app: redisdb 
spec:
  containers:
  - name: rediscontainer1
    image: redis
    ports:
      - name: redis-port
        containerPort: 6379